#!/usr/bin/env python
# coding: utf-8

"""list of commands used by the positioner"""
COMMANDS = dict(ABORT_ALL=0,
                GET_ID=1,
                GET_FIRMWARE_VERSION=2,
                GET_STATUS=3,
                SEND_TRAJECTORY_NEW=10,
                SEND_TRAJECTORY_DATA=11,
                SEND_TRAJECTORY_DATA_END=12,
                SEND_TRAJECTORY_ABORT=13,
                START_TRAJECTORY=14,
                STOP_TRAJECTORY=15,
                START_REVERSE_TRAJECTORY=16,
                START_DEMO_TRAJECTORY=17,
                INITIALIZE_DATUMS=20,
                GOTO_DATUM_ALPHA=21,
                GOTO_DATUM_BETA=22,
                CALIB_MOTORS=26,
                CALIB_MOTOR_ALPHA=27,
                CALIB_MOTOR_BETA=28,
                GET_DATUM_CALIB_ERROR=29,
                GOTO_POSITION_ABSOLUTE=30,
                GOTO_POSITION_RELATIVE=31,
                GET_ACTUAL_POSITION=32,
                SET_ACTUAL_POSITION=33,
                SET_SPEED=40,
                SET_CURRENT=41,
                GET_MOTOR_POWER=42,
                GET_HALL_POS=43,
                GET_HALL_OUTPUT=44,
                START_DATA_STREAMING=50,
                STOP_DATA_STREAMING=51,
                DATA_STREAMING_DATA=52,
                READ_EXT_FLASH=101,
                WRITE_EXT_FLASH=102,
                ERASE_EXT_FLASH=103,
                GET_ALPHA_HALL_CALIB=104,
                GET_BETA_HALL_CALIB=105,
                GET_COGGING_LENGTH=106,
                GET_COGGING_POS=107,
                GET_COGGING_NEG=108,
                GET_COGGING_HOLD=109,
                GET_COGGING_ANGLE=110,
                SET_INCREASE_COLLISION_MARGIN=111,
                SET_LOW_POWER_CURRENT=112,
                GET_LOW_POWER_CURRENT=113,
                SET_APPROACHSPEED=114,
                SET_HALL_SWITCH_ON_COUNT=115,
                SWITCH_ON_HALL_AFTER_MOVE_CMD=116,
                SWITCH_OFF_HALL_AFTER_MOVE_CMD=117,
                SET_ALPHA_CLOSED_LOOP=118,
                SET_ALPHA_CLOSED_LOOP_NO_COLL_DETECT=119,
                SET_ALPHA_OPEN_LOOP=120,
                SET_ALPHA_OPEN_LOOP_NO_COLL_DETECT=121,
                SET_BETA_CLOSED_LOOP=122,
                SET_BETA_CLOSED_LOOP_NO_COLL_DETECT=123,
                SET_BETA_OPEN_LOOP=124,
                SET_BETA_OPEN_LOOP_NO_COLL_DETECT=125,
                SWITCH_ON_LED=126,
                SWITCH_OFF_LED=127,
                SWITCH_ON_PRECISE_ALPHA=128,
                SWITCH_OFF_PRECISE_ALPHA=129,
                SWITCH_ON_PRECISE_BETA=130,
                SWITCH_OFF_PRECISE_BETA=131,
                GET_TEMPERATURE_RAW=132,
                GET_TEMPERATURE=133,
                SET_TEMPERATURE=134,
                GET_TEMPERATURE_PARAM=135,
                SET_TEMPERATURE_PARAM=136,
                SET_PRECISE_CURRENT=137,
                GET_PRECISE_CURRENT=138,
                SEND_NEW_FIRMWARE=200,
                FIRMWARE_DATA=201,
                FIRMWARE_ABORT=202,
                REQUEST_REBOOT=213,
                GET_ROOT_ACCESS=222)

"""list of commands number used by the positioner"""
COMMANDS_NUMBER = {v: k for k, v in COMMANDS.items()}

"""list of responses code used by the positioner"""
RESPONSE_CODE = dict(COMMAND_ACCEPTED=0,
                     VALUE_OUT_OF_RANGE=1,
                     INVALID_TRAJECTORY=2,
                     ALREADY_IN_MOTION=3,
                     NOT_INITIALIZED=4,
                     INCORRECT_AMOUNT_OF_DATA=5,
                     INVALID_BROADCAST_COMMAND=10,
                     INVALID_BOOTLOADER_COMMAND=11,
                     INVALID_COMMAND=12,
                     UNKNOWN_COMMAND=13)

"""list of responses code numbers used by the positioner"""
RESPONSE_CODE_NUMBER = {v: k for k, v in RESPONSE_CODE.items()}
